GET http://localhost:3000/user HTTP/1.1
Accept: application/json
Content-Type: application/json
###
GET http://localhost:3000/user/1005 HTTP/1.1
Accept: application/json
Content-Type: application/json
###
POST http://localhost:3000/user HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "samuel",
    "email": "sam@test.com"
}
###
put http://localhost:3000/user/1001 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "samuel",
    "email": "sam@test.com"
}
### 

DELETE http://localhost:3000/user/1007 HTTP/1.1
Accept: application/json
Content-Type: application/json
